In [1]:
%load_ext autoreload
%autoreload 2

import matplotlib.gridspec as gridspec
import sys
from tifffile import imread

# Change this folder to where the cloned `alignment` repository is
sys.path.insert(0, '/Users/elysiaye/alignment')

# Change this folder to where the cloned `caImageAnalysis` repository is
sys.path.insert(0, '/Users/elysiaye/caImageAnalysis')

# Set the base path to the arinel-et-al_2026 repository
arinel_repo_path = r'/Volumes/Kobi/DOI_animals_good'

from alignment import minmax_scaler

from caImageAnalysis.bruker_2P.bruker_tank import BrukerTank
from caImageAnalysis.mesm import *
from caImageAnalysis.plot import *
from caImageAnalysis.statistics import *
from caImageAnalysis.temporal_new import *

# Notebook 2: DOI Analysis

In [ ]:
# Path where the experiment folders are located
data_folder = arinel_repo_path

successful_fish = [7, 8, 9, 10, 11, 13, 15, 17, 20, 21, 24, 28, 30, 31, 32] # a list of fish_id's I want to use for analysis
region = "sequence"

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

Batch exists. Loading batch.pickle

/Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py:205: GuessedAtParserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 205 of the file /Users/elysiaye/caImageAnalysis/caImageAnalysis/bruker_2P/bruker.py. To get rid of this warning, pass the additional argument 'features="html.parser"' to the BeautifulSoup constructor.

  Bs_data = BeautifulSoup(log)
/opt/homebrew/Cellar/micromamba/2.5.0/envs/mescore/lib/python3.10/site-packages/bs4/builder/__init__.py:545: XMLParsedAsHTMLWarning: It looks like you're parsing an XML document using an HTML parser. If this really is an HTML document (maybe it's XHTML?), you can ignore or filter this warning. If it's XML, you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the lxml package installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.
  warnings.warn(

In [ ]:
# Create a BrukerTank object
tank = BrukerTank(data_folder, successful_fish, prefix='elavl3H2BGCaMP', load_fish=True, region=region)

## Tank temporal pack (single HDF5)

Writes **`temporal_pack.h5`** in the data folder with:
- Group **`metadata/`**: `fish`, `age`, `stimulus`, `concentration`, `plane`, `region`, `roi_index`, `pulse_frames`
- Datasets **`temporal`**, **`raw_temporal`**, **`norm_temporal`**, **`raw_norm_temporal`**: each `(n_rois, T)` float32

Run the next cell once (after `tank` exists). Use `overwrite=True` to recompute each fish's traces. `sort_fish_by_id=True` processes fish in numeric order.

Load later with: `from caImageAnalysis.bruker_2P.bruker_tank import load_temporal_pack_hdf5`

In [3]:
from caImageAnalysis.bruker_2P.bruker_tank import load_temporal_pack_hdf5

# Canonical output path for this notebook run
pack_path = tank.folder_path.joinpath('temporal_pack.h5')

# Build/save pack in one call. frame_mode options: 'strict', 'crop', 'pad'
pack_path = tank.save_tank_temporal_pack(
    out_filename=pack_path.name,
    overwrite=False,
    sort_fish_by_id=True,
    frame_mode='strict',
)

print('Pack path:', pack_path)
print('n_rois:', len(tank.temporal_df), '  T (frames):', len(tank.temporal_df['temporal'].iloc[0]))
print('fish order:', sorted(tank.temporal_df['fish'].unique().tolist()))

saved temporal pack: /Volumes/Kobi/DOI_animals_good/temporal_pack.h5 (n_rois=121950)
Pack path: /Volumes/Kobi/DOI_animals_good/temporal_pack.h5
n_rois: 121950   T (frames): 1606

In [5]:
tank.temporal_df

,fish,age,stimulus,concentration,plane,region,roi_index,temporal,raw_temporal,norm_temporal,raw_norm_temporal,pulse_frames
0,7,8,DOI,0.0,0,sequence_1,5,"[-19.703545, 99.25822, 60.655113, 34.578728, 1...","[-4.32513, 187.73355, 233.4865, 52.48327, 88.4...","[0.0, 0.2655894, 0.17940561, 0.12118849, 0.081...","[0.26243988, 0.3913488, 0.422058, 0.30056942, ...",None
1,7,8,DOI,0.0,0,sequence_1,19,"[669.3365, 578.3861, 501.57898, 432.5788, 372....","[942.787, 335.3025, 624.4087, 416.6232, 348.48...","[1.0, 0.86915547, 0.7586579, 0.65939164, 0.573...","[1.0, 0.4782451, 0.72655195, 0.5480897, 0.4895...",None
2,7,8,DOI,0.0,0,sequence_1,20,"[56.803383, 42.23699, 30.986763, 22.297743, 15...","[195.50224, 42.126938, 98.514114, -24.802755, ...","[0.19080034, 0.14736302, 0.11381458, 0.0879037...","[0.5393721, 0.31377077, 0.39671123, 0.21532322...",None
3,7,8,DOI,0.0,0,sequence_1,21,"[-12.739369, -12.739369, -12.739369, -12.73936...","[-117.012825, -8.234477, -95.62526, -125.75841...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.044897057, 0.11079112, 0.057852887, 0.03959...",None
4,7,8,DOI,0.0,0,sequence_1,22,"[336.41666, 281.0572, 234.20522, 492.31976, 41...","[468.14523, 241.99387, 250.61497, 609.16187, 3...","[0.6574693, 0.55643106, 0.47092015, 0.9420126,...","[0.7121878, 0.508398, 0.5161666, 0.83926105, 0...",None
...,...,...,...,...,...,...,...,...,...,...,...,...
121945,32,7,DOI,50.0,10,sequence_1,482,"[-9.6365595, -9.6365595, -9.6365595, -9.636559...","[-54.21441, -38.11311, -69.30583, -57.75074, -...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.08692133, 0.10777145, 0.067378946, 0.082342...",None
121946,32,7,DOI,50.0,10,sequence_1,485,"[-8.668295, -8.668295, -8.668295, -8.668295, -...","[40.694847, 37.881855, -21.555372, 90.50351, 2...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.511...","[0.19941352, 0.19593976, 0.12254093, 0.2609220...",None
121947,32,7,DOI,50.0,10,sequence_1,488,"[-16.497755, -16.497755, -12.822783, 111.78805...","[-38.63394, -87.82884, 167.48622, 375.8978, 29...","[0.0, 0.0, 0.00533974, 0.18639946, 0.092885256...","[0.06138117, 0.017616391, 0.24474984, 0.430157...",None
121948,32,7,DOI,50.0,10,sequence_1,489,"[-22.004105, -22.004105, 113.65837, 49.015152,...","[11.817449, -0.4575617, 295.92734, 297.30005, ...","[0.0, 0.0, 0.19987847, 0.104636304, 0.05477706...","[0.09656333, 0.0865505, 0.32831433, 0.32943407...",None
121949,32,7,DOI,50.0,10,sequence_1,495,"[-6.1330023, -6.1330023, -6.1330023, -6.133002...","[-12.799304, -26.639719, -4.7458262, 20.258875...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...","[0.06229761, 0.047692765, 0.07079589, 0.097181...",None

In [ ]:
# Optional: reload pack from disk (metadata + 4 matrices)
meta, traces = load_temporal_pack_hdf5(pack_path)
print(meta.head())
print({k: v.shape for k, v in traces.items()})

# ENSURE CORRECT FRAME FOR INJECTION !!!!!!!
injection frame = frame immediately after injection

In [6]:
#### ENSURE CORRECT FRAME FOR INJECTION!!!!

injection_frame = 292  # frame when the injection happens

tank.temporal_df['pulse_frames'] = injection_frame
# Optional legacy pandas HDF5 (may fail on large / object columns):
# tank.temporal_df.to_hdf(tank.folder_path.joinpath('temporal.h5'), key='temporal')
from caImageAnalysis.bruker_2P.bruker_tank import save_temporal_pack_hdf5
save_temporal_pack_hdf5(tank.temporal_df, pack_path)
print('Updated pulse_frames and rewrote pack:', pack_path)

PosixPath('/Volumes/Kobi/DOI_animals_good/temporal_pack.h5')

Standardization for all fish

###  Unroll temporal_df to have each neuron per row

In [ ]:
# # Unroll temporal dataframe
# tank.unroll_temporal_df(overwrite=True, determine_responsive=False)

/Users/minelarinel/caImageAnalysis/caImageAnalysis/temporal_new.py:238: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block0_values] [items->Index(['fish_id', 'plane', 'neuron', 'raw_temporal', 'temporal',
       'raw_norm_temporal', 'norm_temporal', 'roi_index', 'com',
       'pulse_frames'],
      dtype='object')]

  key (str, optional): Key to access neuron data in the DataFrame (default is 'raw_norm_temporal').

Batch exists. Loading batch.pickle

/Users/minelarinel/caImageAnalysis/caImageAnalysis/bruker_2P/bruker_tank.py:243: PerformanceWarning:
your performance may suffer as PyTables will pickle object types that it cannot
map directly to c-types [inferred_type->mixed-integer,key->block2_values] [items->Index(['fish_id', 'plane', 'neuron', 'raw_temporal', 'temporal',
       'raw_norm_temporal', 'norm_temporal', 'roi_index', 'com',
       'pulse_frames', 'stimulus', 'region'],
      dtype='object')]

,fish_id,plane,neuron,raw_temporal,temporal,raw_norm_temporal,norm_temporal,roi_index,com,pulse_frames,age,stimulus,concentration,region
0,3,0,0,"[-118.97967634912155, 82.06825094290441, -56.7...","[-53.125278053424054, -53.125278053424054, -53...","[0.227911195269047, 0.42965515920993935, 0.290...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",61,"[351.848502389236, 115.22950934174044]",None,6,DOI,0.0,sequence_3
1,3,0,1,"[-27.32238268781728, -137.7580210020234, -56.4...","[-40.96850142888577, -40.96850142888577, -40.9...","[0.15668967921105673, 0.09128928417275045, 0.1...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",63,"[345.2710589342763, 117.65648168929722]",None,6,DOI,0.0,sequence_3
2,3,0,2,"[81.2634944833037, -37.442899180712644, -263.5...","[-101.99541588882087, -101.99541588882087, -10...","[0.3556525114853689, 0.2649798932937989, 0.092...","[0.0, 0.0, 0.0, 0.0, 0.09890516953053827, 0.09...",73,"[396.90145579807785, 114.89553162923903]",None,6,DOI,0.0,sequence_3
3,3,0,3,"[-11.496872588027287, 118.15121710147342, -29....","[-46.74973461375902, 14.368444580523445, 7.110...","[0.3445708107122409, 0.44968600609984305, 0.32...","[0.07191379187822475, 0.15378921149330488, 0.1...",77,"[382.50075080456827, 127.09565303355862]",None,6,DOI,0.0,sequence_3
4,3,0,4,"[-73.50865144239015, -171.89859719175362, 65.4...","[-124.56791410714715, -124.56791410714715, -79...","[0.2349044213485234, 0.17417404240392453, 0.32...","[0.0, 0.0, 0.05889411813831915, 0.052784487060...",89,"[391.55156172474665, 119.80591727658047]",None,6,DOI,0.0,sequence_3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12680,3,10,12680,"[88.0491272005183, 21.367853203743874, -15.305...","[2.3441478252804338, 2.3441478252804338, 2.344...","[0.2762979095285762, 0.20340759584282572, 0.16...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.028296912694746067...",1559,"[1000.0513102214707, 520.64991037714]",None,6,DOI,0.0,sequence_3
12681,3,10,12681,"[-76.08985168179173, -95.16474621738304, -38.8...","[2.714434944538299, 2.714434944538299, 2.71443...","[0.06162719530471459, 0.04590949464882359, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1619,"[587.2468893140137, 558.4518715792829]",None,6,DOI,0.0,sequence_3
12682,3,10,12682,"[115.36483358724479, -149.76785682085753, -86....","[-16.058242794991266, -16.058242794991266, -16...","[0.1232128310054621, 0.02078203006595132, 0.04...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1673,"[548.3156868194063, 588.7869903500804]",None,6,DOI,0.0,sequence_3
12683,3,10,12683,"[-130.67465971947388, -127.15535733029631, 96....","[4.605697170835408, 4.605697170835408, 4.60569...","[0.013887962138174276, 0.016229968041190333, 0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1674,"[538.2830694909348, 579.5226023284371]",None,6,DOI,0.0,sequence_3
12684,3,10,12684,"[67.0083382187807, -14.130178953632546, -116.8...","[4.26271762605243, 4.26271762605243, 4.2627176...","[0.20933307558382533, 0.13709656286822317, 0.0...","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",1675,"[554.9736627413184, 586.7898320826421]",None,6,DOI,0.0,sequence_3

raw_temporal: traces obtained from CaImAn
temporal: CaImAn function - denoise (caveat: doesn't do supression) --> denoised data looks good with heatmaps



*** for any analysis & clustering use raw_temporal but for visualizations use temporal

normalized data: normalized to between 0 and 1.

all analyses run with raw_norm_temporal

smoothed out denoising from raw_temporal --> temporal: caiman trained on loads of calcium imaging data
transient=1.5 (second)

caiman knows how long the spike trace would take to come back down

when doing the unroll df plot out the 4 temporal columns to see the differences among the 4

## Spatial organization

#### Before moving forward, align all the fish to the reference brain using the alignment repository and environment. First, run the `3_brain_alignment.ipynb` notebook to align all the individual fish onto a reference GCaMP brain. Then, run the `4_brain_alignment_to_mapzebrain.ipynb` to align the reference GCaMP brain to the mapzebrain atlas. Come back to this notebook after alignment is complete.